### ISSUE TITLE
Rack crashes when trying to get Clamp from the browser

### ISSUE THREAD

**Issue by philippesalembier** [Coirt/Bark#30]
Hi, 

I am unable to get clamp from the browser. As soon as I try to select it, Rack crashes.
I have even tried with a minimal configuration: just with the VCV audio-8 plugin, I go to the browser filter to get Clamp, try to select it... and the crash appears immediately. 

I am using a mac. Here is the last line of the log file. 

[45.371 info src/settings.cpp:194] Saving settings /Users/philippe/Documents/Rack/settings-v1.json
[46.863 info src/window.cpp:33] Loaded font /Users/philippe/Documents/Rack/plugins-v1/Bark/res/GelPen_3.ttf
[46.959 fatal src/main.cpp:45] Fatal signal 11. Stack trace:
14: 1   Rack                                0x00000001097223cd _ZL18fatalSignalHandleri + 45
13: 2   libsystem_platform.dylib            0x00007fff65243b5d _sigtramp + 29
12: 3   ???                                 0x0000000000000008 0x0 + 8
11: 4   Rack                                0x000000010974d2fc _ZN4rack3app12ModuleWidget4drawERKNS_6widget6Widget8DrawArgsE + 92
10: 5   Rack                                0x000000010978688e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
9: 6   Rack                                0x000000010978688e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
8: 7   Rack                                0x000000010978688e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
7: 8   Rack                                0x0000000109786b89 _ZN4rack6widget10ZoomWidget4drawERKNS0_6Widget8DrawArgsE + 121
6: 9   Rack                                0x000000010978688e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
5: 10  Rack                                0x000000010978688e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
4: 11  Rack                                0x0000000109782634 _ZN4rack2ui12ScrollWidget4drawERKNS_6widget6Widget8DrawArgsE + 52
3: 12  Rack                                0x000000010978688e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
2: 13  Rack                                0x000000010973a653 _ZN4rack6Window3runEv + 1395
1: 14  Rack                                0x0000000109721efa main + 1434
0: 15  Rack                                0x00000001096bb034 start + 52

Thanks in advance

**Comment by Coirt** [comment]
I have no way to test or reproduce this crash. Does it happen with my other modules? Trim LFO.

Could be the font could you rename the font in  `/Users/philippe/Documents/Rack/plugins-v1/Bark/res/GelPen_3.ttf` to GelPen_3a.ttf and see if this fixes the crash?

**Comment by philippesalembier** [comment]
Thanks for looking at this!
It seems that the problem only occurs with Clamp and Trim LFO BMP. The Trim LFO Hz seems OK. 

Renaming GelPen_3.ttf does not solve the issue. 

Thanks, 

(I guess you have no access to a mac. Just in case this is useful for you, I am using mac 10.14.6.)

**Comment by Coirt** [comment]
Thanks for the report and confirming it is not the font or other modules.

Have you got the stack trace for the Trim LFO BPM crash?

I will look into setting up a mac VM.

**Comment by philippesalembier** [comment]
Here are two logs corresponding to Trim LFO BPM . The first one is with the original  GelPen_3.ttf.

[11.291 info src/window.cpp:33] Loaded font /Users/philippe/Documents/Rack/plugins-v1/Bark/res/GelPen_3.ttf
[11.394 fatal src/main.cpp:45] Fatal signal 11. Stack trace:
14: 1   Rack                                0x00000001055843cd _ZL18fatalSignalHandleri + 45
13: 2   libsystem_platform.dylib            0x00007fff799bfb5d _sigtramp + 29
12: 3   ???                                 0x000000000000000c 0x0 + 12
11: 4   Rack                                0x00000001055af2fc _ZN4rack3app12ModuleWidget4drawERKNS_6widget6Widget8DrawArgsE + 92
10: 5   Rack                                0x00000001055e888e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
9: 6   Rack                                0x00000001055e888e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
8: 7   Rack                                0x00000001055e888e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
7: 8   Rack                                0x00000001055e8b89 _ZN4rack6widget10ZoomWidget4drawERKNS0_6Widget8DrawArgsE + 121
6: 9   Rack                                0x00000001055e888e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
5: 10  Rack                                0x00000001055e888e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
4: 11  Rack                                0x00000001055e4634 _ZN4rack2ui12ScrollWidget4drawERKNS_6widget6Widget8DrawArgsE + 52
3: 12  Rack                                0x00000001055e888e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
2: 13  Rack                                0x000000010559c653 _ZN4rack6Window3runEv + 1395
1: 14  Rack                                0x0000000105583efa main + 1434
0: 15  Rack                                0x000000010551d034 start + 52

This one occurs if I rename the GelPen_3.ttf file to GelPen_3a.ttf

[3.416 warn src/window.cpp:36] Failed to load font /Users/philippe/Documents/Rack/plugins-v1/Bark/res/GelPen_3.ttf
[4.250 fatal src/main.cpp:45] Fatal signal 11. Stack trace:
15: 1   Rack                                0x000000010710c3cd _ZL18fatalSignalHandleri + 45
14: 2   libsystem_platform.dylib            0x00007fff799bfb5d _sigtramp + 29
13: 3   ???                                 0x000000000000000c 0x0 + 12
12: 4   Rack                                0x00000001071372fc _ZN4rack3app12ModuleWidget4drawERKNS_6widget6Widget8DrawArgsE + 92
11: 5   Rack                                0x000000010717088e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
10: 6   Rack                                0x000000010717088e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
9: 7   Rack                                0x000000010717088e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
8: 8   Rack                                0x0000000107170b89 _ZN4rack6widget10ZoomWidget4drawERKNS0_6Widget8DrawArgsE + 121
7: 9   Rack                                0x000000010717088e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
6: 10  Rack                                0x000000010717088e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
5: 11  Rack                                0x000000010716c634 _ZN4rack2ui12ScrollWidget4drawERKNS_6widget6Widget8DrawArgsE + 52
4: 12  Rack                                0x000000010717088e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
3: 13  Rack                                0x0000000107124653 _ZN4rack6Window3runEv + 1395
2: 14  Rack                                0x000000010710befa main + 1434
1: 15  Rack                                0x00000001070a5034 start + 52
0: 16  ???                                 0x0000000000000001 0x0 + 1

**Comment by Coirt** [comment]
Great Thank you Philippe. Will update when I have a fix.

**Comment by Coirt** [comment]
@philippesalembier I have pushed an update to master that I hope will fix this issue. Could you test by building? If so could you also build the distribution and test this in release Rack 1.1.6.

**Comment by Coirt** [comment]
Okay could you rule the font again by renaming the .tff file?

**Comment by philippesalembier** [comment]
Unfortunately, this does not solve the problem and the crash is still occurring. 
The log ends with:
[8.830 warn src/window.cpp:36] Failed to load font ./plugins/Bark/res/GelPen_3.ttf

**Comment by Coirt** [comment]
Interesting what I changed was the char array that holds the values for the displays. It looks like this was successful for Trim LFO BPM but not for Clamp. I have pushed another update there if you could test this?

**Comment by philippesalembier** [comment]
It seems that this last update was the good one. I was able to select the Clamp module and use
it in a patch. Thanks for the fast reaction!

**Comment by Coirt** [comment]
Excellent that is great to hear, however I am confused because this issue was an array size one. [8] is the correct amount of total chars 😕 I just increased it to [9] 

`{ -, 1, 0, ., 0, 0, 0, 0 }` being the highest number of chars

What's even more confusing is Trim LFO BPM and Trim LFO Hz had the same amount of chars in the volt display (top displays) and Hz was not crashing.

Many thanks for your patience and testing!!
